In [ ]:
import pandas as pd
import numpy as np

df1 = pd.DataFrame ({'A': [1, 2], 'B': [2, 3]}, index = [1, 2])
df2 = pd.DataFrame ({'A': [1, 3], 'B': [2, 10]}, index = [4, 10])
df3 = pd.DataFrame ({'A': [1, 3], 'B': [2, 10]}, index = [11, 12])

df_list = [df1, df2, df3]


def fast_vconcat(df_list):

    first_cols = df_list[0].columns
    all_columns_same = all(first_cols.equals(df.columns) for df in df_list[1:])

    index_names = df_list[0].index.name
    print(index_names)

    if all_columns_same:
        #print('using np concat')
        df = np.vstack(df_list)
        df = pd.DataFrame(df, columns = first_cols, index = np.concatenate([df.index.to_list() for df in df_list]))

    else:
        print('columns not the same, using pd concat')
        df = pd.concat(df_list, axis = 0)
    return df

df = fast_vconcat(df_list)
df

    A   B
1   1   2
2   2   3
4   1   2
10  3  10
11  1   2
12  3  10

In [10]:
df.index.to_frame()

     0
1    1
2    2
4    4
10  10
11  11
12  12